config/routes.rb
Rails.application.routes.draw do
  resources :question_choices
  resources :choices
  resources :questions
  resources :stances
  resources :referendas
  resources :decisions
  resources :terms
  resources :judges
  resources :candidates
  resources :voters
  resources :zips
  resources :divisions
  resources :precincts
  resources :cities
  resources :counties
  resources :states
  resources :countries
  resources :ballots
  get 'home/match_results', to: 'home#match_results', as: 'match_results'
  get 'home/match', to: 'home#match', as: 'match'
  get 'home/bond_detail', to: 'home#bond_detail', as: 'bond_detail'
  get 'home/bonds', to: 'home#bonds', as: 'bonds'
  get 'home/issue_detail', to: 'home#issue_detail', as: 'issue_detail'
  get 'home/issues', to: 'home#issues', as: 'issues'
  get 'home/judge_detail', to: 'home#judge_detail', as: 'judge_detail'
  get 'home/judges', to: 'home#judges', as: 'home_judges'
  get 'home/candidate_detail', to: 'home#candidate_detail', as: 'candidate_detail'
  get 'home/candidates', to: 'home#candidates', as: 'home_candidates'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ballot.rb
class Ballot < ApplicationRecord
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :precinct
  belongs_to :ballot
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :county
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
end

app/models/decision.rb
class Decision < ApplicationRecord
  belongs_to :judge
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :precinct
end

app/models/judge.rb
class Judge < ApplicationRecord
  belongs_to :ballot
end

app/models/precinct.rb
class Precinct < ApplicationRecord
  belongs_to :city
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/referenda.rb
class Referenda < ApplicationRecord
  belongs_to :ballot
end

app/models/stance.rb
class Stance < ApplicationRecord
  belongs_to :referenda
  belongs_to :candidate
  belongs_to :voter
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :candidate
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :zip
end

app/models/zip.rb
class Zip < ApplicationRecord
  belongs_to :precinct
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
  before_action :set_ballot, only: [:show, :edit, :update, :destroy]

  # GET /ballots
  # GET /ballots.json
  def index
    @ballots = Ballot.all
  end

  # GET /ballots/1
  # GET /ballots/1.json
  def show
  end

  # GET /ballots/new
  def new
    @ballot = Ballot.new
  end

  # GET /ballots/1/edit
  def edit
  end

  # POST /ballots
  # POST /ballots.json
  def create
    @ballot = Ballot.new(ballot_params)

    respond_to do |format|
      if @ballot.save
        format.html { redirect_to @ballot, notice: 'Ballot was successfully created.' }
        format.json { render :show, status: :created, location: @ballot }
      else
        format.html { render :new }
        format.json { render json: @ballot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ballots/1
  # PATCH/PUT /ballots/1.json
  def update
    respond_to do |format|
      if @ballot.update(ballot_params)
        format.html { redirect_to @ballot, notice: 'Ballot was successfully updated.' }
        format.json { render :show, status: :ok, location: @ballot }
      else
        format.html { render :edit }
        format.json { render json: @ballot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ballots/1
  # DELETE /ballots/1.json
  def destroy
    @ballot.destroy
    respond_to do |format|
      format.html { redirect_to ballots_url, notice: 'Ballot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ballot
      @ballot = Ballot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ballot_params
      params.require(:ballot).permit(:election_year)
    end
end

app/helpers/ballots_helper.rb
module BallotsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/ballots/_form.html.erb
<%= form_for(ballot) do |f| %>
  <% if ballot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ballot.errors.count, "error") %> prohibited this ballot from being saved:</h2>

      <ul>
      <% ballot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :election_year %>
    <%= f.text_field :election_year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballots/edit.html.erb
<h1>Editing Ballot</h1>

<%= render 'form', ballot: @ballot %>

<%= link_to 'Show', @ballot %> |
<%= link_to 'Back', ballots_path %>

app/views/ballots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ballots</h1>

<table>
  <thead>
    <tr>
      <th>Election year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ballots.each do |ballot| %>
      <tr>
        <td><%= ballot.election_year %></td>
        <td><%= link_to 'Show', ballot %></td>
        <td><%= link_to 'Edit', edit_ballot_path(ballot) %></td>
        <td><%= link_to 'Destroy', ballot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ballot', new_ballot_path %>

app/views/ballots/new.html.erb
<h1>New Ballot</h1>

<%= render 'form', ballot: @ballot %>

<%= link_to 'Back', ballots_path %>

app/views/ballots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Election year:</strong>
  <%= @ballot.election_year %>
</p>

<%= link_to 'Edit', edit_ballot_path(@ballot) %> |
<%= link_to 'Back', ballots_path %>