config/routes.rb
Rails.application.routes.draw do
  resources :question_choices
  resources :choices
  resources :questions
  resources :stances
  resources :referendas
  resources :decisions
  resources :terms
  resources :judges
  resources :candidates
  resources :voters
  resources :zips
  resources :divisions
  resources :precincts
  resources :cities
  resources :counties
  resources :states
  resources :countries
  resources :ballots
  get 'home/match_results', to: 'home#match_results', as: 'match_results'
  get 'home/match', to: 'home#match', as: 'match'
  get 'home/bond_detail', to: 'home#bond_detail', as: 'bond_detail'
  get 'home/bonds', to: 'home#bonds', as: 'bonds'
  get 'home/issue_detail', to: 'home#issue_detail', as: 'issue_detail'
  get 'home/issues', to: 'home#issues', as: 'issues'
  get 'home/judge_detail', to: 'home#judge_detail', as: 'judge_detail'
  get 'home/judges', to: 'home#judges', as: 'home_judges'
  get 'home/candidate_detail', to: 'home#candidate_detail', as: 'candidate_detail'
  get 'home/candidates', to: 'home#candidates', as: 'home_candidates'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ballot.rb
class Ballot < ApplicationRecord
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :precinct
  belongs_to :ballot
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :county
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
end

app/models/decision.rb
class Decision < ApplicationRecord
  belongs_to :judge
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :precinct
end

app/models/judge.rb
class Judge < ApplicationRecord
  belongs_to :ballot
end

app/models/precinct.rb
class Precinct < ApplicationRecord
  belongs_to :city
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/referenda.rb
class Referenda < ApplicationRecord
  belongs_to :ballot
end

app/models/stance.rb
class Stance < ApplicationRecord
  belongs_to :referenda
  belongs_to :candidate
  belongs_to :voter
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :candidate
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :zip
end

app/models/zip.rb
class Zip < ApplicationRecord
  belongs_to :precinct
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:choice, :question_id)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/choices/_form.html.erb
<%= form_for(choice) do |f| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :choice %>
    <%= f.text_field :choice %>
  </div>

  <div class="field">
    <%= f.label :question_id %>
    <%= f.text_field :question_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th>Choice</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.choice %></td>
        <td><%= choice.question %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Choice:</strong>
  <%= @choice.choice %>
</p>

<p>
  <strong>Question:</strong>
  <%= @choice.question %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>