config/routes.rb
Rails.application.routes.draw do
  resources :question_choices
  resources :choices
  resources :questions
  resources :stances
  resources :referendas
  resources :decisions
  resources :terms
  resources :judges
  resources :candidates
  resources :voters
  resources :zips
  resources :divisions
  resources :precincts
  resources :cities
  resources :counties
  resources :states
  resources :countries
  resources :ballots
  get 'home/match_results', to: 'home#match_results', as: 'match_results'
  get 'home/match', to: 'home#match', as: 'match'
  get 'home/bond_detail', to: 'home#bond_detail', as: 'bond_detail'
  get 'home/bonds', to: 'home#bonds', as: 'bonds'
  get 'home/issue_detail', to: 'home#issue_detail', as: 'issue_detail'
  get 'home/issues', to: 'home#issues', as: 'issues'
  get 'home/judge_detail', to: 'home#judge_detail', as: 'judge_detail'
  get 'home/judges', to: 'home#judges', as: 'home_judges'
  get 'home/candidate_detail', to: 'home#candidate_detail', as: 'candidate_detail'
  get 'home/candidates', to: 'home#candidates', as: 'home_candidates'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ballot.rb
class Ballot < ApplicationRecord
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :precinct
  belongs_to :ballot
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :county
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
end

app/models/decision.rb
class Decision < ApplicationRecord
  belongs_to :judge
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :precinct
end

app/models/judge.rb
class Judge < ApplicationRecord
  belongs_to :ballot
end

app/models/precinct.rb
class Precinct < ApplicationRecord
  belongs_to :city
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/referenda.rb
class Referenda < ApplicationRecord
  belongs_to :ballot
end

app/models/stance.rb
class Stance < ApplicationRecord
  belongs_to :referenda
  belongs_to :candidate
  belongs_to :voter
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :candidate
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :zip
end

app/models/zip.rb
class Zip < ApplicationRecord
  belongs_to :precinct
end

app/controllers/referendas_controller.rb
class ReferendasController < ApplicationController
  before_action :set_referenda, only: [:show, :edit, :update, :destroy]

  # GET /referendas
  # GET /referendas.json
  def index
    @referendas = Referenda.all
  end

  # GET /referendas/1
  # GET /referendas/1.json
  def show
  end

  # GET /referendas/new
  def new
    @referenda = Referenda.new
  end

  # GET /referendas/1/edit
  def edit
  end

  # POST /referendas
  # POST /referendas.json
  def create
    @referenda = Referenda.new(referenda_params)

    respond_to do |format|
      if @referenda.save
        format.html { redirect_to @referenda, notice: 'Referenda was successfully created.' }
        format.json { render :show, status: :created, location: @referenda }
      else
        format.html { render :new }
        format.json { render json: @referenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referendas/1
  # PATCH/PUT /referendas/1.json
  def update
    respond_to do |format|
      if @referenda.update(referenda_params)
        format.html { redirect_to @referenda, notice: 'Referenda was successfully updated.' }
        format.json { render :show, status: :ok, location: @referenda }
      else
        format.html { render :edit }
        format.json { render json: @referenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referendas/1
  # DELETE /referendas/1.json
  def destroy
    @referenda.destroy
    respond_to do |format|
      format.html { redirect_to referendas_url, notice: 'Referenda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_referenda
      @referenda = Referenda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def referenda_params
      params.require(:referenda).permit(:referenda_title, :referenda_desc, :referenda_type, :ballot_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/referendas_helper.rb
module ReferendasHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/referendas/_form.html.erb
<%= form_for(referenda) do |f| %>
  <% if referenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(referenda.errors.count, "error") %> prohibited this referenda from being saved:</h2>

      <ul>
      <% referenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :referenda_title %>
    <%= f.text_field :referenda_title %>
  </div>

  <div class="field">
    <%= f.label :referenda_desc %>
    <%= f.text_field :referenda_desc %>
  </div>

  <div class="field">
    <%= f.label :referenda_type %>
    <%= f.text_field :referenda_type %>
  </div>

  <div class="field">
    <%= f.label :ballot_id %>
    <%= f.text_field :ballot_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/referendas/edit.html.erb
<h1>Editing Referenda</h1>

<%= render 'form', referenda: @referenda %>

<%= link_to 'Show', @referenda %> |
<%= link_to 'Back', referendas_path %>

app/views/referendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Referendas</h1>

<table>
  <thead>
    <tr>
      <th>Referenda title</th>
      <th>Referenda desc</th>
      <th>Referenda type</th>
      <th>Ballot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referendas.each do |referenda| %>
      <tr>
        <td><%= referenda.referenda_title %></td>
        <td><%= referenda.referenda_desc %></td>
        <td><%= referenda.referenda_type %></td>
        <td><%= referenda.ballot %></td>
        <td><%= link_to 'Show', referenda %></td>
        <td><%= link_to 'Edit', edit_referenda_path(referenda) %></td>
        <td><%= link_to 'Destroy', referenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referenda', new_referenda_path %>

app/views/referendas/new.html.erb
<h1>New Referenda</h1>

<%= render 'form', referenda: @referenda %>

<%= link_to 'Back', referendas_path %>

app/views/referendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Referenda title:</strong>
  <%= @referenda.referenda_title %>
</p>

<p>
  <strong>Referenda desc:</strong>
  <%= @referenda.referenda_desc %>
</p>

<p>
  <strong>Referenda type:</strong>
  <%= @referenda.referenda_type %>
</p>

<p>
  <strong>Ballot:</strong>
  <%= @referenda.ballot %>
</p>

<%= link_to 'Edit', edit_referenda_path(@referenda) %> |
<%= link_to 'Back', referendas_path %>