config/routes.rb
Rails.application.routes.draw do
  resources :question_choices
  resources :choices
  resources :questions
  resources :stances
  resources :referendas
  resources :decisions
  resources :terms
  resources :judges
  resources :candidates
  resources :voters
  resources :zips
  resources :divisions
  resources :precincts
  resources :cities
  resources :counties
  resources :states
  resources :countries
  resources :ballots
  get 'home/match_results', to: 'home#match_results', as: 'match_results'
  get 'home/match', to: 'home#match', as: 'match'
  get 'home/bond_detail', to: 'home#bond_detail', as: 'bond_detail'
  get 'home/bonds', to: 'home#bonds', as: 'bonds'
  get 'home/issue_detail', to: 'home#issue_detail', as: 'issue_detail'
  get 'home/issues', to: 'home#issues', as: 'issues'
  get 'home/judge_detail', to: 'home#judge_detail', as: 'judge_detail'
  get 'home/judges', to: 'home#judges', as: 'home_judges'
  get 'home/candidate_detail', to: 'home#candidate_detail', as: 'candidate_detail'
  get 'home/candidates', to: 'home#candidates', as: 'home_candidates'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ballot.rb
class Ballot < ApplicationRecord
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :precinct
  belongs_to :ballot
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :county
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
end

app/models/decision.rb
class Decision < ApplicationRecord
  belongs_to :judge
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :precinct
end

app/models/judge.rb
class Judge < ApplicationRecord
  belongs_to :ballot
end

app/models/precinct.rb
class Precinct < ApplicationRecord
  belongs_to :city
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/referenda.rb
class Referenda < ApplicationRecord
  belongs_to :ballot
end

app/models/stance.rb
class Stance < ApplicationRecord
  belongs_to :referenda
  belongs_to :candidate
  belongs_to :voter
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :candidate
end

app/models/voter.rb
class Voter < ApplicationRecord
  belongs_to :zip
end

app/models/zip.rb
class Zip < ApplicationRecord
  belongs_to :precinct
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def match_results
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/home/bond_detail.html.erb
<h1>{{referenda.title}} where {{referenda.type}} == 'bond'</h1>
<h2>{{referenda.type}}</h2>
<p>{{referenda.desc}}</p>

app/views/home/bonds.html.erb
<h1>Bonds</h1>
<p>Select a bond&hellip;</p>
<table class="detail-table bond-table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Type</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{referenda.title}}</td>
            <td>{{referenda.desc}}</td>
            <td>{{referenda.type}}</td>
            <td><a href="{{this_will_link_to_an_issue}}">More&hellip;</a></td>
        </tr>
        <tr>
            <td>{{referenda.title}}</td>
            <td>{{referenda.desc}}</td>
            <td>{{referenda.type}}</td>
            <td><a href="{{this_will_link_to_an_issue}}">More&hellip;</a></td>
        </tr>
    </tbody>
</table>

app/views/home/candidate_detail.html.erb
<h1>{{first_name}} {{last_name}}</h1>
<h2>{{term.position_title}} (Most Recent), {{isEncumbent}}, {{pol_aff}}<br />
{{precinct.precinct_num}}, {{city.city_name}}, {{county.county_name}}, {{state.state_name}}, {{country.country_name}}</h2>
<ul id="contact_options">
    <li><a href="mailto:{{email}}">E-mail</a></li>
    <li><a href="{{pol_URL}}">Website</a></li>
</ul>
<p>{{biography}}</p>
<h3>Stances</h3>
<table class="detail-table candidate-stance-table">
  <thead>
      <tr>
          <th>Topic</th>
          <th>Stance</th>
          <th>Stance Source</th>
          <th>Details</th>
      </tr>
  </thead>
  <tbody>
      <tr>
          <td>{{referenda.title}}</td>
          <td>{{stance.stance}}</td>
          <td>{{stance.stance_source_URL}}</td>
          <td><a href="{{this_will_link_to_referenda_or_issue}}">More&hellip;</a></td>
      </tr>
  </tbody>
</table>

<h3>Past Terms</h3>
<table class="detail-table past-terms-table">
    <thead>
        <tr>
            <th>Position Title</th>
            <th>Term Start</th>
            <th>Term End</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{term.position_title}}</td>
            <td>{{term.termStart}}</td>
            <td>{{term.termEnd}}</td>
        </tr>
    </tbody>
</table>

app/views/home/candidates.html.erb
<h1>Candidates</h1>
<p>Select a candidate&hellip;</p>
<table class="detail-table candidate-table">
    <thead>
        <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Party</th>
            <th>Encumbent</th>
            <th>Precinct</th>
            <th>E-Mail</th>
            <th>Website</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{last_name}}</td>
            <td>{{first_name}}</td>
            <td>{{pol_aff}}</td>
            <td>{{isEncumbent}}</td>
            <td>{{precinct_id}}</td>
            <td>{{email}}</td>
            <td>{{pol_URL}}</td>
            <td><a href="{{this_will_link_to_candidate}}">More&hellip;</a></td>
        </tr>
        <tr>
            <td>{{last_name}}</td>
            <td>{{first_name}}</td>
            <td>{{pol_aff}}</td>
            <td>{{isEncumbent}}</td>
            <td>{{district_id}}</td>
            <td>{{email}}</td>
            <td>{{pol_URL}}</td>
            <td><a href="{{this_will_link_to_candidate}}">More&hellip;</a></td>
        </tr>
    </tbody>
</table>

app/views/home/index.html.erb
<h1>What is myVote?</h1>
<p>
    <strong>Election season is upon us.</strong>
    Don't know who to vote for? Don't know what the issues are?</p>
<p>
    <strong>myVote</strong>
    serves as a way to to get all those answers in one place. Review the
    <%= link_to "candidates", candidates_path %>,
    <%= link_to "judges", judges_path %>,
    <%= link_to "issues", issues_path %>, and
    <%= link_to "bonds", bonds_path %>,
    for your area, and use our
    <%= link_to "completely anonymous matching tool", match_path %>
    to find the candidate that supports the issues you care about.
    <strong>No registration required.</strong>
</p>

app/views/home/issue_detail.html.erb
<h1>{{referenda.title}} where {{referenda.type}} == 'issue'</h1>
<h2>{{referenda.type}}</h2>
<p>{{referenda.desc}}</p>

<h3>Candidates' Stances</h3>
<table class="detail-table issue-stance-table">
    <thead>
        <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Stance</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{candidate.last_name}}</td>
            <td>{{candidate.first_name}}</td>
            <td>{{stance.stance}}</td>
            <td><a href="{{this_will_link_to_candidate}}">More&hellip;</a></td>
        </tr>
    </tbody>
</table>

app/views/home/issues.html.erb
<h1>Issues</h1>
<p>Select an issue&hellip;</p>
<table class="detail-table issue-table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Type</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{referenda.title}}</td>
            <td>{{referenda.desc}}</td>
            <td>{{referenda.type}}</td>
            <td><a href="{{this_will_link_to_an_issue}}">More&hellip;</a></td>
        </tr>
        <tr>
            <td>{{referenda.title}}</td>
            <td>{{referenda.desc}}</td>
            <td>{{referenda.type}}</td>
            <td><a href="{{this_will_link_to_an_issue}}">More&hellip;</a></td>
        </tr>
    </tbody>
</table>

app/views/home/judge_detail.html.erb
<h1>{{first_name}} {{last_name}}</h1>
<h2>{{isSitting}}, {{pol_aff}}<br />
{{district.district_num}}, {{city.city_name}}, {{county.county_name}}, {{state.state_name}}, {{country.country_name}}</h2>
<ul id="contact_options">
    <li><a href="mailto:{{email}}">E-mail</a></li>
</ul>
<p>{{biography}}</p>
<h3>Recent Decisions</h3>
<table class="detail-table judge-decision-table">
  <thead>
      <tr>
          <th>Title</th>
          <th>Decision</th>
          <th>Decision Source</th>
      </tr>
  </thead>
  <tbody>
      <tr>
          <td>{{decision.title}}</td>
          <td>{{decision.position}}</td>
          <td>{{decision.decision_source_URL}}</td>
      </tr>
  </tbody>
</table>

app/views/home/judges.html.erb
<h1>Judges</h1>
<p>Select a judge&hellip;</p>
<table class="detail-table judge-table">
    <thead>
        <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Party</th>
            <th>Sitting</th>
            <th>Precinct</th>
            <th>E-Mail</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{last_name}}</td>
            <td>{{first_name}}</td>
            <td>{{pol_aff}}</td>
            <td>{{isSitting}}</td>
            <td>{{precinct_id}}</td>
            <td>{{email}}</td>
            <td><a href="{{this_will_link_to_candidate}}">More&hellip;</a></td>
        </tr>
        <tr>
            <td>{{last_name}}</td>
            <td>{{first_name}}</td>
            <td>{{pol_aff}}</td>
            <td>{{isSitting}}</td>
            <td>{{precinct_id}}</td>
            <td>{{email}}</td>
            <td><a href="{{this_will_link_to_candidate}}">More&hellip;</a></td>
        </tr>
    </tbody>
</table>

app/views/home/match.html.erb
<h1>Find <span class="underline">Your</span> Match</h1>
<h3>Instructions</h3>
<p>Here, we'll give you the ten (10) most important issues as sourced by
    <a href="http://www.gallup.com/poll/1675/most-important-problem.aspx">Gallup Polling</a>. Enter your ZIP code, choose your stance, and see your matches on the next page. As noted below in the disclaimer, no identifiable information will be linked with you, and any data storage is anonymous and purely for analytical purposes.</p>
<!-- Begin Quiz -->
<div class="match-q-a">
    <h1>Enter your ZIP Code</h1>
    <label for="zip">ZIP Code</label>
    <input id="zip" type="text" maxlength="5" autofocus placeholder="12345" onkeypress='return event.charCode >= 48 && event.charCode <= 57'/>
</div>
<!-- Begin Question -->
<div class="match-q-b">
    <h1>1) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q1" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q1" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q1" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q1" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q1" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-a">
    <h1>2) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q2" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q2" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q2" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q2" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q2" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-b">
    <h1>3) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q1" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q3" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q3" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q3" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q3" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-a">
    <h1>4) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q4" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q4" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q4" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q4" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q4" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-b">
    <h1>5) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q5" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q5" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q5" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q5" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q5" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-a">
    <h1>6) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q6" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q6" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q6" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q6" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q6" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-b">
    <h1>7) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q7" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q7" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q7" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q7" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q7" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-a">
    <h1>8) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q8" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q8" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q8" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q8" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q8" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-b">
    <h1>9) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q9" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q9" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q9" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q9" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q9" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<!-- Begin Question -->
<div class="match-q-a">
    <h1>10) {{question.question}}</h1>
    <p>{{question.question_desc}}</p>
    <div class="match-choices">
        <span class="choice">
            <input type="radio" name="q10" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q10" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q10" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q10" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
        <span class="choice">
            <input type="radio" name="q10" value="{{question_choices.choice}}"/>
            <label for="{{question_choices.choice}}">{{question_choices.choice}}</label>
        </span>
    </div>
</div>
<!-- End Question -->
<input id="submit-match" type="submit" value="Find Your Match" />
<!-- End Quiz -->

app/views/home/match_results.html.erb
<h1>
    <span class="underline">Your</span>
    Match Results</h1>
<p>Based on the the answers you gave on the previous page, we have matched you with the following candidates based on your ZIP Code ({{voter.zip_id.zip_code}}). See how you match up with them.</p>
<hr/>
<input id="mail-results" type="button" value="E-Mail Results"/>
<hr/>
<!-- BEGIN MATCH -->
<div class="match">
    <h2>You v. <a href="{{link_to_candidate}}">{{candidate.first_name}} {{candidate.last_name}}</a></h2>
    <h3>Total Match</h3>
    <p>Psuedocode:<br/>percent = 0; foreach (voter-choice and candidate-choice) { if(voter-choice === candidate-choice) percent++; }<br/>
        percent = percent * 100;<br/>
        Use percent in values for class below and percentage value.</p>
    <div class="match-container">
        <div class="match-percentage per-30">{{percent}}%</div>
    </div>
    <table class="detail-table match-table match-results-table">
        <thead>
            <tr>
                <th>You (voter.id)</th>
                <th>Match</th>
                <th>Them (candidate.id)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="match-table-question" colspan="3">{{question.question}}</td>
            </tr>
            <tr>
                <td>{{question_choices.choice}}</td>
                <td>YES/NO<br/>
                    if voter answer === candidate answer</td>
                <td>{{question_choices.choice}}</td>
            </tr>
            <tr>
                <td class="match-table-question" colspan="3">{{question.question}}</td>
            </tr>
            <tr>
                <td>{{question_choices.choice}}</td>
                <td>YES/NO<br/>
                    if voter answer === candidate answer</td>
                <td>{{question_choices.choice}}</td>
            </tr>
        </tbody>
    </table>
    [...]
    <hr />
</div>
<!-- END -->
<!-- BEGIN MATCH -->
<div class="match">
    <h2>You v. <a href="{{link_to_candidate}}">{{candidate.first_name}} {{candidate.last_name}}</a></h2>
    <h3>Total Match</h3>
    <div class="match-container">
        <div class="match-percentage per-70">70%</div>
    </div>
    <table class="detail-table match-table match-results-table">
        <thead>
            <tr>
                <th>You (voter.id)</th>
                <th>Match</th>
                <th>Them (candidate.id)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="match-table-question" colspan="3">{{question.question}}</td>
            </tr>
            <tr>
                <td>{{question_choices.choice}}</td>
                <td>YES</td>
                <td>{{question_choices.choice}}</td>
            </tr>
            <tr>
                <td class="match-table-question" colspan="3">{{question.question}}</td>
            </tr>
            <tr>
                <td>{{question_choices.choice}}</td>
                <td>YES</td>
                <td>{{question_choices.choice}}</td>
            </tr>
        </tbody>
    </table>
    [...]
    <hr />
</div>
<!-- END -->